[[feed]]
name = "Kaffa"
url = "https://kaffa.im/feed.xml"

[[feed]]
name = "奇客Solidot–传递最新科技情报"
url = "https://www.solidot.org/index.rss"

[[feed]]
name = "阮一峰的网络日志"
url = "https://www.ruanyifeng.com/blog/atom.xml"

[[feed]]
name = "槿呈Goidea"
url = "https://justgoidea.com/rss.xml"

[[feed]]
name = "李昆"
url = "https://likun.cc/rss.xml"